### PR TITLE
Dx 2225

### PR DESCRIPTION
**Pull request by suluvai**
Added StarkEx Transfer to Sample Game

https://github.com/immutable/sample-unreal-game/assets/4755020/97378fc5-8d8d-4d1e-a125-660536ba0034

### CODE REVIEW

**Review by nattb8 — COMMENTED** [review]
Can you try and package the game properly, too, to make sure it works? Not just playing it from the editor.

You should be able to do it by going to Project Launcher -> Click Advanced -> Change the Data Build to By the book -> Launch to WIndows/Mac. ([UE4 it's in the Build Options menu](https://docs.unrealengine.com/4.26/en-US/SharingAndReleasing/Deployment/ProjectLauncher/), [UE5.2 is in Platforms menu](https://docs.unrealengine.com/5.2/en-US/using-the-project-launcher-in-unreal-engine/))

**Comment by dom-murray** [comment]
Can you push the `endlessrun/API/ImmutableApi` files as well? They're missing at the moment.

**Comment by suluvai** [comment]
> Can you push the `endlessrun/API/ImmutableApi` files as well? They're missing at the moment.

they are not required anymore. All the logic in moved into to the Blueprint nodes

**Comment by dom-murray** [comment]
image
I've tried on my main account and a brand new and both failed at the burning tokens stage.

**Comment by suluvai** [comment]
Hey @nattb8 I had merge conflicts after your PR is merged into main for following 2 assets
1. MainMenu.asset
2. Gameoverscreen.uasset

I compared manually and added your only change as below for both assets, please confirm it is correct and is the only change made?

image

**Comment by suluvai** [comment]
> image I've tried on my main account and a brand new and both failed at the burning tokens stage.

ok, interesting. Let's try and huddle tomorrow to see what is the issue.

**Comment by suluvai** [comment]
> Can you try and package the game properly, too, to make sure it works? Not just playing it from the editor.
> 
> You should be able to do it by going to Project Launcher -> Click Advanced -> Change the Data Build to By the book -> Launch to WIndows/Mac. ([UE4 it's in the Build Options menu](https://docs.unrealengine.com/4.26/en-US/SharingAndReleasing/Deployment/ProjectLauncher/), [UE5.2 is in Platforms menu](https://docs.unrealengine.com/5.2/en-US/using-the-project-launcher-in-unreal-engine/))

Yup, tested on both Windows and Mac. Works fine.

**Comment by nattb8** [comment]
Failing for me as well 
image

**Comment by suluvai** [comment]
@dom-murray @nattb8 This PR should be good to merge now, I fixed up all the above mentioned issues. Please let me know if anymore issues.

**Review by dom-murray — APPROVED** [review]

**Pull request merged**
